name: templates/go/vertical/http-service
on:
  push:
    paths:
      - 'templates/go/vertical/http-service/**'
jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Lint
        uses: moorara/actions/go-lint@main
        with:
          path: ./templates/go/vertical/http-service
  test:
    name: Test Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        id: test
        uses: moorara/actions/go-cover@main
        with:
          path: ./templates/go/vertical/http-service
  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Build Binary
        working-directory: ./templates/go/vertical/http-service
        run: make build
      - name: Build Docker Image
        working-directory: ./templates/go/vertical/http-service
        run: make docker save-docker
